name: Simple Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run a one-line script
      run: echo "Hello, world!"

    - name: Checkmarx AST Github Action
      uses: Checkmarx/ast-github-action@2.0.23
      with:
        base_uri: https://eu.ast.checkmarx.net/
        cx_tenant: ast_abdul_ansari
        cx_client_id: Gitactions_P
        cx_client_secret: KbqZQbBi7bPDyI0vtLLkv58xysN2wLrc
