name: Checkmarx One Scan
on:
  pull_request:
    branches:
      - master

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

  sca_scan:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Run SCA Scan
        uses: checkmarx/ast-github-action@main
        with:
          CX_APIKEY: ${{ secrets.CX_APIKEY }}
          additional_params: --scan-types sca --threshold "sca-critical=35"

  sast_scan:
    runs-on: ubuntu-latest
    needs: sca_scan
    steps:
      - name: Run SAST Scan
        uses: checkmarx/ast-github-action@main
        with:
          CX_APIKEY: ${{ secrets.CX_APIKEY }}
          additional_params: --scan-types sast --threshold "sast-critical=35"
